services:
  - type: worker
    name: keyword-alert-bot
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MY_USER_ID
        sync: false
